# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_auto_20170227_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='player_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
